### ISSUE TITLE
Trouble with compilation 

### ISSUE THREAD

**Issue by ghost** [sinshu/managed-doom#10]
It says I need .net 3.1 for MeltySynth. I can't get 3.1 to appear in my target framework selection. Help would be greatly appreciated.

 - Thanks in advance, AvienJ

**Comment by sinshu** [comment]
Are you using Visual Studio?
If you are using Visual Studio,
* is the version 2019?
* which target frameworks do you have?

**Comment by AvienJ** [comment]
Sorry, it took me so long to respond. Yes, I am using Visual Studio 2019.

Here is a list of my target frameworks:
![2021-06-30 18_40_16-](https://user-images.githubusercontent.com/44857143/124052149-b94b2000-d9d2-11eb-8cc9-9417d628a60a.png)

**Comment by KoalaBear84** [comment]
Looks like you need the SDK for .NET 5 currently.

See: https://github.com/sinshu/managed-doom/blob/master/ManagedDoom/ManagedDoom.csproj there is "net5.0" which is the newer .NET "Core", not the older .NET Framework.

1. https://dotnet.microsoft.com/download/dotnet
2. Go to .NET 5
3. Download the SDK for Windows

For current Windows 64-bit it's this one:
https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-5.0.301-windows-x64-installer

**Comment by AvienJ** [comment]
I've downloaded both the x86 and x64 versions and the list still hasn't changed. Yes, I have preview features on.

**Comment by sinshu** [comment]
This seems a problem of Visual Studio, so I cannot be of much help to you...

As far as I searched, some solutions are available in the following link:
https://stackoverflow.com/questions/60843091/net-5-not-available-in-visual-studio-2019

* .NET 5 requires Visual Studio 2019 Version 16.8 or later. Update your Visual Studio if its version is old.
* Do a repair with Visual Studio Installer might solve the problem.

**Comment by AvienJ** [comment]
I edited the csproj file and manually set the framework to "net50" and success!

**Comment by DamianSuess** [comment]
The latest version uses .NET 6. Just check the .csproj file.
This issue should be closed
