### ISSUE TITLE
No IWAD was Found !

### ISSUE THREAD

**Issue by BlueMystical** [sinshu/managed-doom#11]
Im getting the "No IWAD was Found !" error

Am i missing something?
![333](https://user-images.githubusercontent.com/10116951/124662851-b7c0a280-de7f-11eb-8683-1fc1746e77d6.png)

**Comment by sinshu** [comment]
You need to copy one of the following files from the commercial Doom games.

* DOOM.WAD (Ultimate Doom)
* DOOM2.WAD (Doom II)
* PLTONIA.WAD (Final Doom)
* TNT.WAD (Final Doom)

If you want to try before buying a commercial game, the shareware version is available.
Download "DOOM1.WAD" from the following page and copy to the directory of managed-doom.exe.

https://doomwiki.org/wiki/DOOM1.WAD

If you like the game, you can buy the commercial version in Steam.
