### ISSUE TITLE
Exception: No IWAD was found!

### ISSUE THREAD

**Issue by mjebrahimi** [sinshu/managed-doom#2]
That’s great. I really enjoy this. Thanks

Program gives `System.Exception: No IWAD was found!` error when running. I found that it needs ".WAD" files.

I want to ask you, can you put [these files](https://pc-freak.net/blog/doom-1-doom-2-doom-3-game-wad-files-for-download-playing-doom-on-debian-linux-via-freedoom-open-source-doom-engine/) in the publishing folder so that no one gets in trouble during the execution?

**Comment by IceReaper** [comment]
You need a game to play. Either buy a doom game and copy the wad file or use a fan made game wad to play fan made games.

**Comment by mjebrahimi** [comment]
You're right.
