### ISSUE TITLE
.WAD Paths

### ISSUE THREAD

**Issue by Gobblerofpotatoes** [sinshu/managed-doom#34]
I am having trouble locating where I should place the wad files, is there any advice you could give?

thx

**Comment by IceReaper** [comment]
https://github.com/sinshu/managed-doom/blob/master/ManagedDoom/src/ConfigUtilities.cs#L51 next to the .exe ;)

**Comment by Gobblerofpotatoes** [comment]
Might I ask where is the .exe
Thx :)

**Comment by sinshu** [comment]
Normally, you can find it in the following locations:

Release mode:
your-project-directory\ManagedDoom\bin\Release\net7.0

Debug mode:
your-project-directory\ManagedDoom\bin\Debug\net7.0

**Comment by Gobblerofpotatoes** [comment]
Thankyou so much
